### PR TITLE
Update to collector v0.29.0

### LINKED ISSUE #52: Update to collector v0.29.0
Similar to #48 but for v0.29.0.

### PR DESCRIPTION
**Pull request by himanshu007-creator**
Resolves #52

### CODE REVIEW

**Comment by jpkrohling** [comment]
Didn't it require a change to address https://github.com/open-telemetry/opentelemetry-collector/pull/3268 ?

**Comment by himanshu007-creator** [comment]
> Didn't it require a change to address [open-telemetry/opentelemetry-collector#3268](https://github.com/open-telemetry/opentelemetry-collector/pull/3268) ?

sorry, can you explain?!

**Comment by jpkrohling** [comment]
The builder uses API from the collector, including the one that got changed by the PR open-telemetry/opentelemetry-collector#3268 . The tests are indeed failing, as the builder needs to use the new API:

```
2021-06-25T12:57:03.006Z	ERROR	cmd/root.go:91	failed to run	{"error": "failed to compile the OpenTelemetry Collector distribution: exit status 2. Output: \"# github.com/open-telemetry/opentelemetry-collector-builder/test/nocore\\n./main.go:40:26: undefined: service.AppSettings\\n\""}
github.com/go-logr/zapr.(*zapLogger).Error
	/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
github.com/open-telemetry/opentelemetry-collector-builder/cmd.Execute
	/home/runner/work/opentelemetry-collector-builder/opentelemetry-collector-builder/cmd/root.go:91
main.main
	/home/runner/work/opentelemetry-collector-builder/opentelemetry-collector-builder/main.go:25
runtime.main
	/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/proc.go:225
failed to compile the OpenTelemetry Collector distribution: exit status 2. Output: "# github.com/open-telemetry/opentelemetry-collector-builder/test/nocore\n./main.go:40:26: undefined: service.AppSettings\n"
exit status 1
```
 
I wonder how you were able to run the builder locally.

**Comment by jpkrohling** [comment]
By the way, here's the place to fix it: https://github.com/open-telemetry/opentelemetry-collector-builder/blob/a468961ec2882aeebe60293dd86696fd057c1ab8/internal/scaffold/main.go#L56

**Comment by himanshu007-creator** [comment]
> The builder uses API from the collector, including the one that got changed by the PR [open-telemetry/opentelemetry-collector#3268](https://github.com/open-telemetry/opentelemetry-collector/pull/3268) . The tests are indeed failing, as the builder needs to use the new API:
> 
> ```
> 2021-06-25T12:57:03.006Z	ERROR	cmd/root.go:91	failed to run	{"error": "failed to compile the OpenTelemetry Collector distribution: exit status 2. Output: \"# github.com/open-telemetry/opentelemetry-collector-builder/test/nocore\\n./main.go:40:26: undefined: service.AppSettings\\n\""}
> github.com/go-logr/zapr.(*zapLogger).Error
> 	/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
> github.com/open-telemetry/opentelemetry-collector-builder/cmd.Execute
> 	/home/runner/work/opentelemetry-collector-builder/opentelemetry-collector-builder/cmd/root.go:91
> main.main
> 	/home/runner/work/opentelemetry-collector-builder/opentelemetry-collector-builder/main.go:25
> runtime.main
> 	/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/proc.go:225
> failed to compile the OpenTelemetry Collector distribution: exit status 2. Output: "# github.com/open-telemetry/opentelemetry-collector-builder/test/nocore\n./main.go:40:26: undefined: service.AppSettings\n"
> exit status 1
> ```
> 
> I wonder how you were able to run the builder locally.

I didnt😬, just changes the code here.

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
Thank you for this PR!

**Pull request merged**
